decoration {
    rounding = 12
    inactive_opacity = 0.8
    blur {
        enabled = true
        size = 2
        passes = 5
	noise = 0.016
	xray = 1
	popups = true
	ignore_opacity = true
    }
    drop_shadow = true
    shadow_range = 20
    shadow_render_power = 4
    # 设置投影颜色
    col.shadow = 0xffa7caff #86AAEC rgba(1a1a1aee)
    col.shadow_inactive = 0x50000000
}
